name: Release
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch"
        required: true
        default: "main"
      tag:
        description: "Release Tag"



jobs:
  binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, arm64]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} make build
      -
        name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: compose-spec
          path: ./bin/*
          if-no-files-found: error

  release:
    permissions:
      contents: write # to create a release (ncipollo/release-action)
    runs-on: ubuntu-latest
    needs:
      - binary
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: compose
          path: bin/release
      -
        name: GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ github.event.inputs.branch }}
